name: Github Actions CI/CD Pipeline v5

on:
  push:
    branches:
      - main

jobs:
  My-Deploy-Job:
    runs-on: ubuntu-latest
    steps:
      - name: 해당 OS에 레포지토리 파일 업로드하기
        uses: actions/checkout@v4

      - name: 잘 생성됐는지 확인하기
        run: |
          ls -a

      - name: 빌드를 위한 jdk 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: 설치 완료 테스트
        run: java -version

      - name: 빌드 권한 부여
        run: chmod +x ./gradlew

      - name: jar파일 빌드
        run: ./gradlew clean build

      - name: env 파일 생성
        run: |
          printf "%s" "${{ secrets.ENV }}" > .env

      - name: AWS 리소스에 접근할 수 있게 credentials 설정
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: ECR 로그인
        uses: aws-actions/amazon-ecr-login@v2

      - name: 이미지 생성 및 ECR에 업로드
        run: |
          docker build -t ${{ secrets.AWS_ECR_IMAGE_URL }} .
          docker push ${{ secrets.AWS_ECR_IMAGE_URL }}

      - name: 압축하기
        run: tar -czvf $GITHUB_SHA.tar.gz compose.yml appspec.yml scripts .env


      - name: S3에 프로젝트 압축파일 업로드
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.tar.gz s3://dummy-server/$GITHUB_SHA.tar.gz

      - name: Code Deploy를 활용해 EC2에 프로젝트 코드 배포
        run: aws deploy create-deployment
          --application-name dummy-server-deploy
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name Production
          --s3-location bucket=dummy-server,bundleType=tgz,key=$GITHUB_SHA.tar.gz
